### PR TITLE
Trim Redundant Badges from README

### PR DESCRIPTION
**Pull request by will-rice**
trimming redundant badges to keep the badges on one line.

### CODE REVIEW

**Review by space-pope — COMMENTED** [review]
This doesn't actually fit on one line for me:
image

If it were me, I'd get rid of the code style badge (people only need to know that if they want to contribute, and it can be covered in that section of the readme) and order them as
```
version | build | coverage | license
```

...but that's all subjective. If this version is based on things you commonly see in Python repos, it's fine too. I do think it's an improvement.

**Comment by will-rice** [comment]
when I looked at it in vscode, it was one line. It's still two for me also in the browser.

**Comment by space-pope** [comment]
Sounds like a different column width for the editor's markdown renderer than GitHub's.

**Comment by roppem9** [comment]
lgtm

**Review by roppem9 — APPROVED** [review]
lgtm

**Comment by will-rice** [comment]
@space-pope approve and merge ;)

**Pull request merged**
