### PR TITLE
Documentation Build Fix

### PR DESCRIPTION
**Pull request by will-rice**
This should fix the documentation issue with `spokestack.readthedocs.io`. The problem was with `sphinx-autodoc` overwriting the existing `.rst` files which were already set to use the sphinx autodoc feature correctly. This change in workflow is reflected in the README.

### CODE REVIEW

**Review by brentspell — APPROVED** [review]
it's a bummer that all this stuff has to be committed every time the docs change, but lgtm

**Comment by will-rice** [comment]
yeah I feel like there has to be a way around that because locally you just need the `.rst` files. I'll look into it, maybe I can specify a custom build on readthedocs.

**Comment by will-rice** [comment]
at some point I want to set up a post merge build as well because I'm doing it manually right now.

**Comment by brentspell** [comment]
we only really need to rebuild the docs whenever we release, so it can be included in that process

**Comment by will-rice** [comment]
oh right. that makes more sense.

**Pull request merged**
